name: Run Flask Hello App

on:
  workflow_dispatch:

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flask
        run: pip install flask

      - name: Run Flask app
        run: python main.py
